import Link from 'next/link'
import { AutoGeneratedComponent } from '@/components/demo/auto-generated-component'

/**
 * 🤖 자동화 데모 페이지
 *
 * 이 페이지는 Claude Code가 자동으로 생성했습니다.
 * 접속: http://localhost:3000/demo
 */
export default function DemoPage() {
  return (
    <div className="min-h-screen bg-zinc-950 p-8">
      <div className="mx-auto max-w-4xl space-y-6">
        {/* 헤더 */}
        <div className="text-center">
          <h1 className="mb-2 text-4xl font-bold text-white">🤖 Claude Code 자동화 데모</h1>
          <p className="text-zinc-400">이 페이지는 완전 자동으로 생성되었습니다</p>
        </div>

        {/* 자동 생성된 컴포넌트들 */}
        <AutoGeneratedComponent title="컴포넌트 #1" />
        <AutoGeneratedComponent title="컴포넌트 #2" />
        <AutoGeneratedComponent title="컴포넌트 #3" />

        {/* 정보 카드 */}
        <div className="rounded-lg border border-zinc-800 bg-zinc-900 p-6">
          <h3 className="mb-4 text-xl font-bold text-white">✅ 자동으로 생성된 것들</h3>
          <ul className="space-y-2 text-zinc-300">
            <li>✅ React 컴포넌트 (TypeScript)</li>
            <li>✅ Next.js 페이지</li>
            <li>✅ Tailwind CSS 스타일</li>
            <li>✅ QETTA 디자인 시스템</li>
            <li>✅ VS Code에서 자동 감지됨</li>
          </ul>
        </div>

        {/* 링크 */}
        <div className="text-center">
          <Link
            href="/"
            className="inline-block rounded-md bg-zinc-600 px-6 py-3 text-white transition-colors hover:bg-zinc-500"
          >
            ← 홈으로 돌아가기
          </Link>
        </div>
      </div>
    </div>
  )
}
