# QETTA Funding/Sponsor Configuration
# GitHub Sponsors 및 기타 후원 플랫폼 설정

# github: [username]  # GitHub Sponsors 계정이 있다면 활성화
# patreon: username
# open_collective: qetta
# ko_fi: qetta
# custom: ['https://www.buymeacoffee.com/qetta']
