'use client'

import { useState } from 'react'

interface AutoGeneratedComponentProps {
  title?: string
}

/**
 * 🤖 이 컴포넌트는 Claude Code가 자동으로 생성했습니다!
 * 생성 시각: 2026-02-02
 *
 * 기능:
 * - 카운터 증가/감소
 * - QETTA 디자인 시스템 (Zinc 컬러)
 * - TypeScript 타입 안전성
 */
export function AutoGeneratedComponent({ title = 'Auto-Generated' }: AutoGeneratedComponentProps) {
  const [count, setCount] = useState(0)

  return (
    <div className="rounded-lg border border-zinc-800 bg-zinc-950 p-6">
      <h2 className="mb-4 text-2xl font-bold text-white">🤖 {title}</h2>

      <div className="mb-4 text-zinc-400">이 컴포넌트는 Claude Code가 자동으로 생성했습니다!</div>

      <div className="flex items-center gap-4">
        <button
          onClick={() => setCount(count - 1)}
          className="rounded-md bg-zinc-800 px-4 py-2 text-white transition-colors hover:bg-zinc-700"
        >
          -
        </button>

        <span className="text-3xl font-bold text-white">{count}</span>

        <button
          onClick={() => setCount(count + 1)}
          className="rounded-md bg-zinc-600 px-4 py-2 text-white transition-colors hover:bg-zinc-500"
        >
          +
        </button>
      </div>

      <div className="mt-4 text-sm text-zinc-500">
        ✅ TypeScript ✅ Tailwind CSS ✅ QETTA Design System
      </div>
    </div>
  )
}
