/**
 * BIO_PHARMA Industry BLOCK
 * Category: healthcare
 * KSIC: 21 (바이오/제약)
 *
 * v2.1: HEALTHCARE 블록 흡수
 */
import type { EnrichedIndustryBlock } from './types'

export const BIO_PHARMA_BLOCK: EnrichedIndustryBlock = {
  id: 'BIO_PHARMA',
  name: 'Biotech, Pharmaceuticals & Healthcare',
  nameKo: '바이오/제약/헬스케어',
  category: 'healthcare',
  description: 'Biopharmaceutical R&D, drug development, medical devices, healthcare data, regulatory submissions, and laboratory compliance reporting',
  descriptionKo: '바이오 의약품 R&D, 신약 개발, 의료기기, 헬스케어 데이터, 규제 제출, 실험실 준수 보고서',

  terminology: [
    {
      id: 'ind',
      korean: '임상시험계획승인',
      english: 'Investigational New Drug',
      category: 'regulation',
      description: '신약 임상시험 승인 신청',
      aliases: ['IND', '임상계획승인'],
      regulatoryRef: 'FDA 21 CFR Part 312',
      examples: ['IND 신청', 'Phase 1 허가'],
    },
    {
      id: 'nda',
      korean: '신약 허가 신청',
      english: 'New Drug Application',
      category: 'regulation',
      description: '신약 시판 허가 신청',
      aliases: ['NDA', '품목허가'],
      regulatoryRef: 'FDA 21 CFR Part 314',
      examples: ['NDA 제출', '시판 허가'],
    },
    {
      id: 'glp',
      korean: '우수실험실관리기준',
      english: 'Good Laboratory Practice',
      category: 'standard',
      description: '비임상 시험 품질 보증 기준',
      aliases: ['GLP', '비임상시험기준'],
      regulatoryRef: 'OECD GLP Principles',
      examples: ['GLP 인증', '독성 시험'],
    },
    {
      id: 'ctd',
      korean: '공통기술문서',
      english: 'Common Technical Document',
      category: 'document',
      description: 'ICH 신약 허가 신청 표준 양식',
      aliases: ['CTD', 'eCTD'],
      regulatoryRef: 'ICH M4',
      examples: ['Module 2 Overview', 'Module 3 Quality'],
    },
    {
      id: 'biologics',
      korean: '바이오 의약품',
      english: 'Biological Products',
      category: 'product',
      description: '생물학적 제제 (항체, 백신 등)',
      aliases: ['biologics', '생물의약품'],
      examples: ['단클론항체', 'mRNA 백신'],
    },
    {
      id: 'cdmo',
      korean: '의약품 위탁개발생산',
      english: 'Contract Development and Manufacturing Organization',
      category: 'service',
      description: '바이오 의약품 위탁 개발 및 생산',
      aliases: ['CDMO', 'CMO'],
      examples: ['공정 개발', '상업 생산'],
    },
    {
      id: 'batch-record',
      korean: '제조기록서',
      english: 'Batch Production Record',
      category: 'document',
      description: 'GMP 제조 이력 기록',
      aliases: ['BPR', '배치 기록'],
      regulatoryRef: '약사법 시행규칙 별표 5',
      examples: ['제조 지시', '품질 검사'],
    },
    // === 의료기기/헬스케어 관련 (HEALTHCARE 흡수) ===
    {
      id: 'mfds-approval',
      korean: '식약처 허가',
      english: 'MFDS Approval',
      category: 'regulation',
      description: '식품의약품안전처 의료기기 허가',
      aliases: ['식약처', 'MFDS', '허가'],
      regulatoryRef: '의료기기법 제6조',
      examples: ['1등급 신고', '2~4등급 허가'],
    },
    {
      id: 'clinical-trial',
      korean: '임상시험',
      english: 'Clinical Trial',
      category: 'process',
      description: '의약품/의료기기 임상 시험',
      aliases: ['clinical trial', '임상'],
      examples: ['Phase I/II/III', 'IRB 승인'],
    },
    {
      id: 'irb',
      korean: '기관생명윤리위원회',
      english: 'Institutional Review Board',
      category: 'organization',
      description: '임상시험 윤리 심사 위원회',
      aliases: ['IRB', '생명윤리위원회'],
      regulatoryRef: '생명윤리 및 안전에 관한 법률',
      examples: ['IRB 승인', '피험자 보호'],
    },
    {
      id: 'udi',
      korean: '의료기기 고유식별자',
      english: 'Unique Device Identifier',
      category: 'standard',
      description: '의료기기 추적 고유 번호',
      aliases: ['UDI', '고유식별자'],
      regulatoryRef: 'FDA UDI Regulation',
      examples: ['바코드', 'RFID'],
    },
  ],

  templates: [
    {
      id: 'ind-submission',
      name: 'IND Submission Package',
      nameKo: 'IND 제출 문서',
      format: 'PDF',
      sections: [
        'Form FDA 1571',
        'Investigator Brochure',
        'Protocol',
        'CMC (Chemistry, Manufacturing, Controls)',
        'Pharmacology/Toxicology',
        'Previous Human Experience',
      ],
      estimatedGenerationTime: 300,
    },
    {
      id: 'ctd-module-3',
      name: 'CTD Module 3 (Quality)',
      nameKo: 'CTD Module 3 (품질)',
      format: 'PDF',
      sections: [
        '3.2.S Drug Substance',
        '3.2.P Drug Product',
        'Specifications',
        'Analytical Methods',
        'Stability Data',
      ],
      estimatedGenerationTime: 240,
    },
    {
      id: 'glp-study-report',
      name: 'GLP Study Report',
      nameKo: 'GLP 시험 보고서',
      format: 'DOCX',
      sections: [
        'Study Summary',
        'Materials and Methods',
        'Results',
        'Conclusions',
        'GLP Compliance Statement',
        'Quality Assurance Statement',
      ],
      estimatedGenerationTime: 180,
    },
  ],

  rules: [
    {
      id: 'glp-compliance',
      name: 'GLP Compliance for Nonclinical Studies',
      description: '비임상시험 GLP 준수 의무',
      condition: 'nonclinical_study = true',
      action: 'Conduct study under GLP-certified facility',
      severity: 'error',
      regulatoryRef: 'OECD GLP Principles',
    },
    {
      id: 'ind-safety-reporting',
      name: 'IND Safety Reporting (15-day)',
      description: 'IND 중대한 이상반응 15일 이내 보고',
      condition: 'serious_adverse_reaction = true AND ind_active = true',
      action: 'Submit IND Safety Report to FDA within 15 days',
      severity: 'error',
      regulatoryRef: 'FDA 21 CFR 312.32',
    },
    {
      id: 'batch-release-approval',
      name: 'Batch Release Approval',
      description: '품질 승인 없이 출하 금지',
      condition: 'batch_produced = true',
      action: 'QA must approve batch before release',
      severity: 'error',
      regulatoryRef: 'EU GMP Annex 16',
    },
  ],

  keywords: ['IND', 'NDA', 'GLP', 'CTD', 'biologics', 'CDMO', 'clinical trial', 'IRB', 'UDI', 'MFDS', '신약', '바이오', '의료기기', 'KSIC 21'],
  regulatoryBodies: ['식품의약품안전처', 'FDA', 'EMA', 'ICH', 'CE', 'ISO'],
  color: 'rose',

  tokenBudget: {
    metadata: 50,
    terminology: 500,
    full: 2000,
  },
}
