/**
 * ENVIRONMENT Industry BLOCK
 * Category: energyEnvironment
 * KSIC: 35, 38 (환경/에너지)
 *
 * v2.1: ENERGY 블록 흡수
 * Extracted from lib/skill-engine/skills/tms/index.ts
 */
import type { EnrichedIndustryBlock } from './types'

export const ENVIRONMENT_BLOCK: EnrichedIndustryBlock = {
  id: 'ENVIRONMENT',
  name: 'Environment & Energy',
  nameKo: '환경/에너지',
  category: 'energyEnvironment',
  description: 'Air quality monitoring, emission tracking, energy management, renewable energy, and environmental compliance reporting',
  descriptionKo: '대기질 모니터링, 배출량 추적, 에너지 관리, 신재생에너지, 환경 규제 준수 보고서 생성',

  terminology: [
    {
      id: 'nox',
      korean: '질소산화물',
      english: 'Nitrogen Oxides',
      category: 'pollutant',
      unit: 'ppm',
      description: '연소 과정에서 발생하는 질소 화합물',
      aliases: ['NOx', '질소 산화물'],
      legalLimit: 200,
      regulatoryRef: '대기환경보전법 시행규칙 별표 8',
      validationRange: { min: 0, max: 1000 },
      examples: ['보일러 배출가스', '소각로 배출가스'],
    },
    {
      id: 'sox',
      korean: '황산화물',
      english: 'Sulfur Oxides',
      category: 'pollutant',
      unit: 'ppm',
      description: '황을 포함한 연료 연소 시 발생',
      aliases: ['SOx', '황 산화물'],
      legalLimit: 150,
      regulatoryRef: '대기환경보전법 시행규칙 별표 8',
      validationRange: { min: 0, max: 500 },
      examples: ['석탄 발전소', '중유 보일러'],
    },
    {
      id: 'pm',
      korean: '미세먼지',
      english: 'Particulate Matter',
      category: 'pollutant',
      unit: 'mg/m³',
      description: '대기 중 부유하는 미세한 입자',
      aliases: ['PM', '먼지', '분진'],
      legalLimit: 30,
      regulatoryRef: '대기환경보전법 시행규칙 별표 8',
      validationRange: { min: 0, max: 200 },
      examples: ['제조 공정', '시멘트 제조'],
    },
    {
      id: 'pm10',
      korean: '미세먼지 (10μm)',
      english: 'PM10',
      category: 'pollutant',
      unit: 'μg/m³',
      description: '직경 10μm 이하 입자',
      aliases: ['PM10', '10마이크론 미세먼지'],
      legalLimit: 100,
      regulatoryRef: '대기환경보전법',
      validationRange: { min: 0, max: 500 },
      examples: ['도로 분진', '건설 현장'],
    },
    {
      id: 'pm25',
      korean: '초미세먼지 (2.5μm)',
      english: 'PM2.5',
      category: 'pollutant',
      unit: 'μg/m³',
      description: '직경 2.5μm 이하 입자',
      aliases: ['PM2.5', 'PM25', '초미세먼지'],
      legalLimit: 50,
      regulatoryRef: '대기환경보전법',
      validationRange: { min: 0, max: 300 },
      examples: ['자동차 배기가스', '연소 시설'],
    },
    {
      id: 'co',
      korean: '일산화탄소',
      english: 'Carbon Monoxide',
      category: 'pollutant',
      unit: 'ppm',
      description: '불완전 연소 시 발생',
      aliases: ['CO', '일산화 탄소'],
      legalLimit: 50,
      regulatoryRef: '대기환경보전법 시행규칙 별표 8',
      validationRange: { min: 0, max: 200 },
      examples: ['가스 보일러', '차량 배기가스'],
    },
    {
      id: 'tms',
      korean: '원격 모니터링 시스템',
      english: 'Tele-Monitoring System',
      category: 'system',
      description: '환경부 굴뚝 원격 감시 시스템',
      aliases: ['TMS', '굴뚝 TMS'],
      examples: ['실시간 배출량 전송', '자동 보고'],
    },
    {
      id: 'cleansys',
      korean: '클린시스',
      english: 'CleanSYS',
      category: 'system',
      description: '환경부 대기오염물질 배출정보 관리 시스템 (cleansys.or.kr)',
      aliases: ['CleanSYS', 'CLEAN SYS'],
      examples: ['배출량 신고', '초과 사유서 제출'],
    },
    {
      id: 'cems',
      korean: '연속측정장치',
      english: 'Continuous Emission Monitoring System',
      category: 'equipment',
      description: '굴뚝 배출가스 연속 측정 장치',
      aliases: ['CEMS', '자동측정기'],
      examples: ['5분 주기 측정', 'TMS 연동'],
    },
    // === 에너지 관련 (ENERGY 흡수) ===
    {
      id: 'carbon-neutral',
      korean: '탄소중립',
      english: 'Carbon Neutrality',
      category: 'policy',
      description: '온실가스 순 배출량 제로 달성',
      aliases: ['탄소중립', 'Net Zero', '2050 탄소중립'],
      regulatoryRef: '탄소중립기본법',
      examples: ['2050 탄소중립', 'RE100'],
    },
    {
      id: 'ess',
      korean: '에너지 저장 장치',
      english: 'Energy Storage System',
      category: 'equipment',
      unit: 'MWh',
      description: '전력 저장 및 공급 시스템',
      aliases: ['ESS', '배터리 저장'],
      examples: ['리튬이온 ESS', 'Peak Shaving'],
    },
    {
      id: 'rec',
      korean: '신재생에너지 인증서',
      english: 'Renewable Energy Certificate',
      category: 'regulation',
      description: '신재생에너지 공급 인증서',
      aliases: ['REC', '공급인증서'],
      regulatoryRef: '신에너지 및 재생에너지 개발·이용·보급 촉진법',
      examples: ['태양광 REC', '풍력 REC'],
    },
    {
      id: 'ghg-emission',
      korean: '온실가스 배출',
      english: 'Greenhouse Gas Emission',
      category: 'pollutant',
      unit: 'tCO2eq',
      description: '온실가스 배출량 (CO2 환산)',
      aliases: ['GHG', '온실가스', 'tCO2'],
      regulatoryRef: '온실가스 배출권의 할당 및 거래에 관한 법률',
      examples: ['Scope 1 배출', 'Scope 2 배출'],
    },
  ],

  templates: [
    {
      id: 'tms-daily-report',
      name: 'Daily Emission Report',
      nameKo: '일일 배출량 보고서',
      format: 'HWP',
      sections: [
        '측정 개요',
        '오염물질별 배출량 (NOx, SOx, PM, CO)',
        '법적 기준 비교',
        '이상치 분석',
        '조치 사항',
      ],
      estimatedGenerationTime: 45,
    },
    {
      id: 'tms-monthly-report',
      name: 'Monthly Environmental Report',
      nameKo: '월간 환경 관리 보고서',
      format: 'HWP',
      sections: [
        '월간 요약',
        '일별 추이 분석',
        '법규 준수 현황',
        '개선 계획',
        '증빙 자료',
      ],
      estimatedGenerationTime: 90,
    },
    {
      id: 'tms-measurement-record',
      name: 'Measurement Record',
      nameKo: '측정기록부',
      format: 'XLSX',
      sections: [
        '측정 일시',
        '측정 항목',
        '측정값',
        '측정자',
        '비고',
      ],
      estimatedGenerationTime: 30,
    },
  ],

  rules: [
    {
      id: 'clean-air-act',
      name: 'Clean Air Conservation Act Compliance',
      description: '대기환경보전법 준수 검사',
      condition: 'NOx > 200ppm OR SOx > 150ppm OR PM > 30mg/m³',
      action: 'Trigger immediate notification and require corrective action report within 24 hours',
      severity: 'error',
      regulatoryRef: '대기환경보전법 제31조 (배출허용기준)',
    },
    {
      id: 'warning-threshold',
      name: 'Warning Threshold (80% of Legal Limit)',
      description: '법적 기준 80% 도달 시 사전 경고',
      condition: 'measurement >= legalLimit * 0.8',
      action: 'Issue warning alert and schedule preventive maintenance',
      severity: 'warning',
      regulatoryRef: 'Internal compliance policy',
    },
    {
      id: 'cleansys-sync',
      name: 'CleanSYS Data Synchronization',
      description: 'CleanSYS 일일 데이터 전송 의무',
      condition: 'daily_report_generated = true',
      action: 'Auto-submit daily emission data to CleanSYS within 24 hours',
      severity: 'info',
      regulatoryRef: '대기환경보전법 시행령 제15조',
    },
  ],

  keywords: ['TMS', 'CleanSYS', 'CEMS', 'air quality', 'emission', 'NOx', 'SOx', 'PM', 'ESS', 'REC', '탄소중립', 'GHG', '환경부', 'KSIC 35-38'],
  regulatoryBodies: ['환경부', 'Ministry of Environment', '국립환경과학원', '산업통상자원부', '한국에너지공단'],
  color: 'emerald',

  tokenBudget: {
    metadata: 50,
    terminology: 500,
    full: 2000,
  },
}
