/**
 * SEMICONDUCTOR Industry BLOCK
 * Category: manufacturing
 */
import type { EnrichedIndustryBlock } from './types'

export const SEMICONDUCTOR_BLOCK: EnrichedIndustryBlock = {
  id: 'SEMICONDUCTOR',
  name: 'Semiconductor Manufacturing',
  nameKo: '반도체 제조',
  category: 'manufacturing',
  description: 'Semiconductor fabrication process control, cleanroom compliance, and yield management reporting',
  descriptionKo: '반도체 공정 관리, 클린룸 준수, 수율 관리 보고서',

  terminology: [
    {
      id: 'wafer-yield',
      korean: '웨이퍼 수율',
      english: 'Wafer Yield',
      category: 'metric',
      unit: '%',
      description: '전체 웨이퍼 중 양품 비율',
      aliases: ['yield', '수율', 'good die'],
      validationRange: { min: 0, max: 100 },
      examples: ['70% 수율', '85% 목표'],
    },
    {
      id: 'critical-dimension',
      korean: '임계 치수',
      english: 'Critical Dimension',
      category: 'metric',
      unit: 'nm',
      description: '패턴 최소 선폭',
      aliases: ['CD', '선폭'],
      validationRange: { min: 1, max: 1000 },
      examples: ['5nm 공정', '7nm 노드'],
    },
    {
      id: 'overlay',
      korean: '정렬도',
      english: 'Overlay',
      category: 'metric',
      unit: 'nm',
      description: '층간 패턴 정렬 정확도',
      aliases: ['OVL', '층간 정렬'],
      validationRange: { min: 0, max: 50 },
      examples: ['±2nm 이내', '정렬 오차'],
    },
    {
      id: 'particle-count',
      korean: '파티클 수',
      english: 'Particle Count',
      category: 'cleanroom',
      unit: 'particles/m³',
      description: '클린룸 내 입자 개수',
      aliases: ['particle', '파티클', '먼지'],
      legalLimit: 100,
      regulatoryRef: 'ISO 14644-1 Class 1',
      examples: ['Class 1 클린룸', '0.1μm 파티클'],
    },
    {
      id: 'etch-rate',
      korean: '식각 속도',
      english: 'Etch Rate',
      category: 'process',
      unit: 'Å/min',
      description: '에칭 공정 속도',
      aliases: ['etch', '식각'],
      examples: ['100Å/min', 'plasma etch'],
    },
    {
      id: 'dep-rate',
      korean: '증착 속도',
      english: 'Deposition Rate',
      category: 'process',
      unit: 'Å/min',
      description: '박막 증착 속도',
      aliases: ['deposition', '증착'],
      examples: ['CVD', 'PVD', 'ALD'],
    },
    {
      id: 'fdc',
      korean: '고장 검출 분류',
      english: 'Fault Detection and Classification',
      category: 'system',
      description: '공정 이상 실시간 감지',
      aliases: ['FDC', 'fault detection'],
      examples: ['SPC 한계 초과', '장비 알람'],
    },
  ],

  templates: [
    {
      id: 'fab-daily-report',
      name: 'Fab Daily Report',
      nameKo: 'Fab 일일 보고서',
      format: 'XLSX',
      sections: [
        'Wafer Start',
        'Wafer Out',
        'Yield Summary',
        'Tool Availability',
        'Critical Issues',
      ],
      estimatedGenerationTime: 60,
    },
    {
      id: 'spc-violation-report',
      name: 'SPC Violation Report',
      nameKo: 'SPC 위반 보고서',
      format: 'PDF',
      sections: [
        '위반 내역',
        '공정 파라미터',
        '영향 분석',
        '시정 조치',
        'FDC 로그',
      ],
      estimatedGenerationTime: 45,
    },
    {
      id: 'cleanroom-audit',
      name: 'Cleanroom Audit Report',
      nameKo: '클린룸 감사 보고서',
      format: 'DOCX',
      sections: [
        'ISO 14644-1 적합성',
        'Particle Count 측정',
        '환경 모니터링 (온도, 습도)',
        '부적합 사항',
        '개선 조치',
      ],
      estimatedGenerationTime: 90,
    },
  ],

  rules: [
    {
      id: 'iso-14644-class-1',
      name: 'ISO 14644-1 Class 1 Compliance',
      description: 'Class 1 클린룸 파티클 기준 준수',
      condition: 'particle_count > 100 particles/m³ (≥0.1μm)',
      action: 'Trigger cleanroom shutdown and contamination investigation',
      severity: 'error',
      regulatoryRef: 'ISO 14644-1:2015',
    },
    {
      id: 'spc-ucl-lcl',
      name: 'SPC Control Limits',
      description: 'SPC 관리 한계 초과 시 공정 중지',
      condition: 'measurement > UCL OR measurement < LCL',
      action: 'Stop lot processing and conduct root cause analysis',
      severity: 'error',
      regulatoryRef: 'SEMI E79 (SPC) Standard',
    },
    {
      id: 'fdc-auto-hold',
      name: 'FDC Auto Hold',
      description: 'FDC 이상 감지 시 자동 홀드',
      condition: 'fdc_alarm = true',
      action: 'Auto-hold lot and notify process engineer',
      severity: 'warning',
      regulatoryRef: 'SEMI E133 (FDC) Standard',
    },
  ],

  keywords: ['wafer', 'yield', 'cleanroom', 'fab', 'SPC', 'FDC', '반도체', '웨이퍼'],
  regulatoryBodies: ['산업통상자원부', 'SEMI', 'ISO'],
  color: 'purple',

  tokenBudget: {
    metadata: 50,
    terminology: 500,
    full: 2000,
  },
}
